github_url = "https://github.com/ENIB-Community/glossarium/"

[version]
current = "0.2.6"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "typst.toml"

[[file]]
src = "justfile"

[[file]]
src = "README.md"

[[file]]
src = "examples/import-terms-from-yaml-file/import-terms-from-yaml-file.typ"

[[file]]
src = "examples/full-example/main.typ"

[[before_commit]]
name = "compile examples"
cmd = "just build-examples"

[[after_push]]
name = "Create local version of package"
cmd = "just local"
